### ISSUE TITLE
window版 启动报错

### ISSUE THREAD

**Issue by yunzhao824** [alibaba/Chat2DB#137]
启动后报错“COMMON_SYSTEM_ERROR: 系统开小差啦，请尝试刷新页面或者联系管理员”，展开数据库表也报这个错，执行查询也报这个错，好像做任何操作都报这个错

**Comment by jipengfei-jpf** [comment]
多少版本？另外能够截个图，看下日志，发我一下。帮助里有打开日志。

**Comment by yunzhao824** [comment]
![1684375379963](https://github.com/alibaba/Chat2DB/assets/39692795/a5c9c6ab-6dd9-4733-97e6-5fad80960041)
[application.log](https://github.com/alibaba/Chat2DB/files/11503670/application.log)

**Comment by jipengfei-jpf** [comment]
是不是没有传密码啊，看报错

**Comment by hunny-sketch** [comment]
我也遇到，日志这样：
`2023-05-18 10:13:13.520 [http-nio-127.0.0.1-10824-exec-7] INFO  c.a.d.s.w.a.a.BusinessExceptionHandler - proceed begin:com.alibaba.dbhub.server.web.api.controller.config.ConfigControllergetChatGptSystemConfig ,param:[]
2023-05-18 10:13:13.535 [http-nio-127.0.0.1-10824-exec-7] INFO  c.a.d.s.w.a.a.BusinessExceptionHandler - proceed end:com.alibaba.dbhub.server.web.api.controller.config.ConfigControllergetChatGptSystemConfig, result:{"data":{},"success":true}, cost:15
2023-05-18 10:13:21.754 [http-nio-127.0.0.1-10824-exec-1] INFO  c.a.d.s.w.a.a.BusinessExceptionHandler - proceed begin:com.alibaba.dbhub.server.web.api.controller.config.ConfigControllergetChatGptSystemConfig ,param:[]
2023-05-18 10:13:21.759 [http-nio-127.0.0.1-10824-exec-1] INFO  c.a.d.s.w.a.a.BusinessExceptionHandler - proceed end:com.alibaba.dbhub.server.web.api.controller.config.ConfigControllergetChatGptSystemConfig, result:{"data":{},"success":true}, cost:6
2023-05-18 10:13:26.563 [Druid-ConnectionPool-Create-1064028521] ERROR c.alibaba.druid.pool.DruidDataSource - create connection SQLException, url: jdbc:mysql://rm-bp1159hheb12r10zr.mysql.rds.aliyuncs.com:3306/xp_usercenter, errorCode 0, state 08S01
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1700)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1792)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2877)
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:120)
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:948)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:818)
	... 6 common frames omitted
Caused by: java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:153)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
	... 9 common frames omitted
2023-05-18 10:13:26.564 [Druid-ConnectionPool-Create-1064028521] INFO  c.a.d.pool.DruidAbstractDataSource - {dataSource-1} failContinuous is true
`

**Comment by jipengfei-jpf** [comment]
看一下是不是配置参数少了，或者网络通吗？

**Comment by jipengfei-jpf** [comment]
方便加钉钉或者微信，详细看一下呢？1 8 0 4 2 0 0 0 7 0 9

**Comment by jipengfei-jpf** [comment]
可以参考：    url: jdbc:mysql://127.0.0.1:3306/xx?useUnicode=true&characterEncoding=utf8&useSSL=false

增加参数useUnicode=true&characterEncoding=utf8&useSSL=false

**Comment by yunzhao824** [comment]
刚安装完成的时候没报错的，密码肯定是对的，因为刚开始的时候，能够把这个连接下的所有数据库都展示出来，从我做了一个操作后就一直报错了，就是我查了一个很大的表，没有给条件和限制数量的参数，报了内存溢出了，然后就一直报错了，所有跟数据库的交互操作都会报错

**Comment by yunzhao824** [comment]
> 可以参考： url: jdbc:mysql://127.0.0.1:3306/xx?useUnicode=true&characterEncoding=utf8&useSSL=false
> 
> 增加参数useUnicode=true&characterEncoding=utf8&useSSL=false

不用加这个，卸载重装后不报错了，请参考我上面关于问题出现的操作过程的描述，你们应该是能够找到一些优化的点的。

**Comment by jipengfei-jpf** [comment]
明白了，知道原因了，我再去优化下。

**Comment by jipengfei-jpf** [comment]
1.0.5已修复
